vim.keymap.set('n', '<leader>tt', ':TestNearest<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>tT', ':TestFile<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>ta', ':TestSuite<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>tl', ':TestLast<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>tg', ':TestVisit<CR>', { noremap = true, silent = true })
