vim.opt.textwidth=79
vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab=true
vim.opt.cindent=true
vim.opt.colorcolumn="79"
vim.opt.smartindent = true
vim.opt.fileformat = "unix"
